//! Language definitions: keyword/type tables, comment + token rules, indentation,
//! and the sample set for each supported language.
//!
//! The syntax highlighter (`syntax::highlight`) and the game state are both driven
//! by `LanguageSpec`, so adding a language is almost entirely data: append a sample
//! module, define a `LanguageSpec`, and add it to `Language` + `ALL`.

use super::samples;

/// How a single quote `'` should be tokenized for a language.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum SingleQuote {
    /// `'a'` is a character/rune literal (C, C++, Java, Kotlin, Go, Rust).
    Char,
    /// `'...'` is a string literal (JavaScript, TypeScript, Python).
    Str,
    /// Single quotes are not string/char delimiters (Swift).
    None,
}

/// Everything the highlighter and game logic need to support one language.
pub struct LanguageSpec {
    pub name: &'static str,
    /// A short emoji shown beside the language in the menu and title.
    pub emoji: &'static str,
    pub keywords: &'static [&'static str],
    pub types: &'static [&'static str],
    /// Line-comment prefix, e.g. `//` or `#`.
    pub line_comment: &'static str,
    /// Block-comment delimiters, e.g. `("/*", "*/")`. `None` if unsupported.
    pub block_comment: Option<(&'static str, &'static str)>,
    pub single_quote: SingleQuote,
    /// Backtick template strings (JavaScript/TypeScript).
    pub backtick_string: bool,
    /// Rust lifetimes (`'a`).
    pub lifetimes: bool,
    /// Rust `ident!` macros.
    pub macros: bool,
    /// Rust `#[attribute]` syntax.
    pub rust_attributes: bool,
    /// C/C++ preprocessor directives (`#include`, `#define`).
    pub preprocessor: bool,
    /// Decorators / annotations (`@Override`, `@decorator`).
    pub decorators: bool,
    /// Spaces inserted for a Tab keystroke.
    pub indent_spaces: usize,
    pub samples: &'static [(&'static str, &'static str)],
}

/// Supported languages, in menu order.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Language {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    Go,
    Java,
    Kotlin,
    Swift,
    C,
    Cpp,
}

/// Languages in the order they appear in the selection menu.
pub const ALL: &[Language] = &[
    Language::Rust,
    Language::Python,
    Language::JavaScript,
    Language::TypeScript,
    Language::Go,
    Language::Java,
    Language::Kotlin,
    Language::Swift,
    Language::C,
    Language::Cpp,
];

impl Language {
    /// The static spec backing this language.
    pub fn spec(self) -> &'static LanguageSpec {
        match self {
            Language::Rust => &RUST,
            Language::Python => &PYTHON,
            Language::JavaScript => &JAVASCRIPT,
            Language::TypeScript => &TYPESCRIPT,
            Language::Go => &GO,
            Language::Java => &JAVA,
            Language::Kotlin => &KOTLIN,
            Language::Swift => &SWIFT,
            Language::C => &C,
            Language::Cpp => &CPP,
        }
    }

    pub fn name(self) -> &'static str {
        self.spec().name
    }
}

// ── Rust ────────────────────────────────────────────────────────────────────
const RUST_KEYWORDS: &[&str] = &[
    "fn", "let", "mut", "if", "else", "match", "struct", "enum", "impl", "pub", "use", "mod",
    "crate", "super", "self", "Self", "for", "while", "loop", "return", "break", "continue",
    "where", "trait", "type", "const", "static", "unsafe", "async", "await", "move", "ref", "in",
    "as", "dyn", "true", "false", "Some", "None", "Ok", "Err",
];
const RUST_TYPES: &[&str] = &[
    "i8",
    "i16",
    "i32",
    "i64",
    "i128",
    "isize",
    "u8",
    "u16",
    "u32",
    "u64",
    "u128",
    "usize",
    "f32",
    "f64",
    "bool",
    "char",
    "str",
    "String",
    "Vec",
    "Option",
    "Result",
    "Box",
    "Rc",
    "Arc",
    "RefCell",
    "Cell",
    "HashMap",
    "HashSet",
    "BTreeMap",
    "BTreeSet",
    "VecDeque",
    "LinkedList",
    "Mutex",
    "RwLock",
    "Cow",
    "Pin",
    "PhantomData",
    "Iterator",
    "IntoIterator",
    "FromIterator",
    "Ord",
    "PartialOrd",
    "Eq",
    "PartialEq",
    "Clone",
    "Copy",
    "Default",
    "Debug",
    "Display",
    "Hash",
    "Send",
    "Sync",
    "From",
    "Into",
    "AsRef",
    "AsMut",
    "Deref",
    "DerefMut",
    "Drop",
    "Fn",
    "FnMut",
    "FnOnce",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Index",
    "IndexMut",
];
static RUST: LanguageSpec = LanguageSpec {
    name: "Rust",
    emoji: "🦀",
    keywords: RUST_KEYWORDS,
    types: RUST_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: false,
    lifetimes: true,
    macros: true,
    rust_attributes: true,
    preprocessor: false,
    decorators: false,
    indent_spaces: 4,
    samples: samples::rust::SAMPLES,
};

// ── Python ──────────────────────────────────────────────────────────────────
const PYTHON_KEYWORDS: &[&str] = &[
    "def", "class", "if", "elif", "else", "for", "while", "return", "import", "from", "as", "with",
    "try", "except", "finally", "raise", "pass", "break", "continue", "lambda", "yield", "global",
    "nonlocal", "in", "is", "not", "and", "or", "None", "True", "False", "async", "await", "del",
    "assert", "self", "cls", "match", "case",
];
const PYTHON_TYPES: &[&str] = &[
    "int",
    "float",
    "str",
    "bool",
    "list",
    "dict",
    "tuple",
    "set",
    "frozenset",
    "bytes",
    "bytearray",
    "complex",
    "object",
    "type",
    "range",
    "Exception",
    "ValueError",
    "TypeError",
    "KeyError",
    "Optional",
    "List",
    "Dict",
    "Tuple",
    "Any",
];
static PYTHON: LanguageSpec = LanguageSpec {
    name: "Python",
    emoji: "🐍",
    keywords: PYTHON_KEYWORDS,
    types: PYTHON_TYPES,
    line_comment: "#",
    block_comment: None,
    single_quote: SingleQuote::Str,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: true,
    indent_spaces: 4,
    samples: samples::python::SAMPLES,
};

// ── JavaScript ──────────────────────────────────────────────────────────────
const JS_KEYWORDS: &[&str] = &[
    "var",
    "let",
    "const",
    "function",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "class",
    "extends",
    "super",
    "new",
    "this",
    "typeof",
    "instanceof",
    "in",
    "of",
    "delete",
    "void",
    "try",
    "catch",
    "finally",
    "throw",
    "async",
    "await",
    "yield",
    "import",
    "export",
    "from",
    "as",
    "null",
    "undefined",
    "true",
    "false",
    "get",
    "set",
    "static",
];
const JS_TYPES: &[&str] = &[
    "Object", "Array", "String", "Number", "Boolean", "Promise", "Map", "Set", "Symbol", "Math",
    "JSON", "Date", "RegExp", "Error", "Function", "BigInt",
];
static JAVASCRIPT: LanguageSpec = LanguageSpec {
    name: "JavaScript",
    emoji: "🟨",
    keywords: JS_KEYWORDS,
    types: JS_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Str,
    backtick_string: true,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: false,
    indent_spaces: 2,
    samples: samples::javascript::SAMPLES,
};

// ── TypeScript ──────────────────────────────────────────────────────────────
const TS_KEYWORDS: &[&str] = &[
    "var",
    "let",
    "const",
    "function",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "class",
    "extends",
    "super",
    "new",
    "this",
    "typeof",
    "instanceof",
    "in",
    "of",
    "delete",
    "void",
    "try",
    "catch",
    "finally",
    "throw",
    "async",
    "await",
    "yield",
    "import",
    "export",
    "from",
    "as",
    "null",
    "undefined",
    "true",
    "false",
    "get",
    "set",
    "static",
    "interface",
    "type",
    "enum",
    "namespace",
    "declare",
    "public",
    "private",
    "protected",
    "readonly",
    "abstract",
    "implements",
    "keyof",
    "infer",
    "is",
    "asserts",
    "satisfies",
    "override",
    "module",
];
const TS_TYPES: &[&str] = &[
    "string", "number", "boolean", "any", "unknown", "never", "void", "object", "bigint", "symbol",
    "Object", "Array", "String", "Number", "Boolean", "Promise", "Map", "Set", "Symbol", "Math",
    "JSON", "Date", "RegExp", "Error", "Partial", "Readonly", "Record", "Pick", "Omit", "Required",
];
static TYPESCRIPT: LanguageSpec = LanguageSpec {
    name: "TypeScript",
    emoji: "🟦",
    keywords: TS_KEYWORDS,
    types: TS_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Str,
    backtick_string: true,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: true,
    indent_spaces: 2,
    samples: samples::typescript::SAMPLES,
};

// ── Go ──────────────────────────────────────────────────────────────────────
const GO_KEYWORDS: &[&str] = &[
    "package",
    "import",
    "func",
    "var",
    "const",
    "type",
    "struct",
    "interface",
    "map",
    "chan",
    "go",
    "defer",
    "select",
    "range",
    "if",
    "else",
    "for",
    "switch",
    "case",
    "default",
    "return",
    "break",
    "continue",
    "fallthrough",
    "goto",
    "nil",
    "true",
    "false",
    "iota",
];
const GO_TYPES: &[&str] = &[
    "int",
    "int8",
    "int16",
    "int32",
    "int64",
    "uint",
    "uint8",
    "uint16",
    "uint32",
    "uint64",
    "uintptr",
    "float32",
    "float64",
    "complex64",
    "complex128",
    "byte",
    "rune",
    "string",
    "bool",
    "error",
    "any",
];
static GO: LanguageSpec = LanguageSpec {
    name: "Go",
    emoji: "🐹",
    keywords: GO_KEYWORDS,
    types: GO_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: true,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: false,
    indent_spaces: 4,
    samples: samples::go::SAMPLES,
};

// ── Java ────────────────────────────────────────────────────────────────────
const JAVA_KEYWORDS: &[&str] = &[
    "public",
    "private",
    "protected",
    "class",
    "interface",
    "extends",
    "implements",
    "static",
    "final",
    "void",
    "new",
    "this",
    "super",
    "return",
    "if",
    "else",
    "for",
    "while",
    "do",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "try",
    "catch",
    "finally",
    "throw",
    "throws",
    "import",
    "package",
    "abstract",
    "synchronized",
    "volatile",
    "transient",
    "native",
    "instanceof",
    "enum",
    "true",
    "false",
    "null",
    "record",
    "var",
    "sealed",
    "permits",
    "yield",
];
const JAVA_TYPES: &[&str] = &[
    "int",
    "long",
    "short",
    "byte",
    "char",
    "boolean",
    "float",
    "double",
    "String",
    "Integer",
    "Long",
    "Double",
    "Boolean",
    "Character",
    "Object",
    "List",
    "Map",
    "Set",
    "ArrayList",
    "HashMap",
    "HashSet",
    "Optional",
    "Stream",
    "Collectors",
    "Math",
    "System",
    "Exception",
    "Comparable",
    "Runnable",
];
static JAVA: LanguageSpec = LanguageSpec {
    name: "Java",
    emoji: "☕",
    keywords: JAVA_KEYWORDS,
    types: JAVA_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: true,
    indent_spaces: 4,
    samples: samples::java::SAMPLES,
};

// ── Kotlin ──────────────────────────────────────────────────────────────────
const KOTLIN_KEYWORDS: &[&str] = &[
    "fun",
    "val",
    "var",
    "class",
    "object",
    "interface",
    "if",
    "else",
    "when",
    "for",
    "while",
    "do",
    "return",
    "break",
    "continue",
    "try",
    "catch",
    "finally",
    "throw",
    "import",
    "package",
    "is",
    "in",
    "as",
    "this",
    "super",
    "null",
    "true",
    "false",
    "data",
    "sealed",
    "enum",
    "override",
    "open",
    "abstract",
    "private",
    "public",
    "protected",
    "internal",
    "companion",
    "init",
    "by",
    "where",
    "suspend",
    "lateinit",
    "vararg",
    "inline",
    "reified",
    "operator",
    "infix",
    "out",
    "typealias",
    "constructor",
];
const KOTLIN_TYPES: &[&str] = &[
    "Int",
    "Long",
    "Short",
    "Byte",
    "Char",
    "Boolean",
    "Float",
    "Double",
    "String",
    "List",
    "MutableList",
    "Map",
    "MutableMap",
    "Set",
    "MutableSet",
    "Array",
    "Unit",
    "Any",
    "Nothing",
    "Pair",
    "Triple",
    "Iterable",
    "Sequence",
    "Result",
];
static KOTLIN: LanguageSpec = LanguageSpec {
    name: "Kotlin",
    emoji: "🟪",
    keywords: KOTLIN_KEYWORDS,
    types: KOTLIN_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: true,
    indent_spaces: 4,
    samples: samples::kotlin::SAMPLES,
};

// ── Swift ───────────────────────────────────────────────────────────────────
const SWIFT_KEYWORDS: &[&str] = &[
    "func",
    "let",
    "var",
    "class",
    "struct",
    "enum",
    "protocol",
    "extension",
    "if",
    "else",
    "guard",
    "switch",
    "case",
    "default",
    "for",
    "while",
    "repeat",
    "return",
    "break",
    "continue",
    "in",
    "import",
    "init",
    "deinit",
    "self",
    "super",
    "nil",
    "true",
    "false",
    "throws",
    "throw",
    "try",
    "catch",
    "do",
    "defer",
    "where",
    "as",
    "is",
    "some",
    "any",
    "async",
    "await",
    "mutating",
    "override",
    "public",
    "private",
    "internal",
    "fileprivate",
    "open",
    "static",
    "final",
    "lazy",
    "weak",
    "unowned",
    "associatedtype",
    "typealias",
    "subscript",
    "inout",
    "indirect",
    "convenience",
    "required",
];
const SWIFT_TYPES: &[&str] = &[
    "Int",
    "Int8",
    "Int16",
    "Int32",
    "Int64",
    "UInt",
    "UInt8",
    "UInt32",
    "UInt64",
    "Double",
    "Float",
    "Bool",
    "String",
    "Character",
    "Array",
    "Dictionary",
    "Set",
    "Optional",
    "Any",
    "AnyObject",
    "Void",
    "Result",
    "Error",
    "Comparable",
    "Equatable",
    "Hashable",
];
static SWIFT: LanguageSpec = LanguageSpec {
    name: "Swift",
    emoji: "🐦",
    keywords: SWIFT_KEYWORDS,
    types: SWIFT_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::None,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: false,
    decorators: true,
    indent_spaces: 4,
    samples: samples::swift::SAMPLES,
};

// ── C ───────────────────────────────────────────────────────────────────────
const C_KEYWORDS: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else",
    "enum", "extern", "float", "for", "goto", "if", "inline", "int", "long", "register",
    "restrict", "return", "short", "signed", "sizeof", "static", "struct", "switch", "typedef",
    "union", "unsigned", "void", "volatile", "while", "NULL", "true", "false",
];
const C_TYPES: &[&str] = &[
    "size_t",
    "ssize_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "FILE",
    "ptrdiff_t",
    "wchar_t",
    "va_list",
    "bool",
];
static C: LanguageSpec = LanguageSpec {
    name: "C",
    emoji: "🔧",
    keywords: C_KEYWORDS,
    types: C_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: true,
    decorators: false,
    indent_spaces: 4,
    samples: samples::c::SAMPLES,
};

// ── C++ ─────────────────────────────────────────────────────────────────────
const CPP_KEYWORDS: &[&str] = &[
    "auto",
    "break",
    "case",
    "char",
    "const",
    "continue",
    "default",
    "do",
    "double",
    "else",
    "enum",
    "extern",
    "float",
    "for",
    "goto",
    "if",
    "inline",
    "int",
    "long",
    "register",
    "return",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "typedef",
    "union",
    "unsigned",
    "void",
    "volatile",
    "while",
    "class",
    "namespace",
    "template",
    "typename",
    "public",
    "private",
    "protected",
    "virtual",
    "override",
    "final",
    "new",
    "delete",
    "this",
    "try",
    "catch",
    "throw",
    "using",
    "nullptr",
    "true",
    "false",
    "bool",
    "constexpr",
    "friend",
    "operator",
    "explicit",
    "mutable",
    "noexcept",
    "static_cast",
    "dynamic_cast",
    "reinterpret_cast",
    "const_cast",
    "decltype",
    "concept",
    "requires",
];
const CPP_TYPES: &[&str] = &[
    "std",
    "string",
    "vector",
    "map",
    "unordered_map",
    "set",
    "unordered_set",
    "pair",
    "tuple",
    "array",
    "list",
    "deque",
    "queue",
    "stack",
    "shared_ptr",
    "unique_ptr",
    "weak_ptr",
    "size_t",
    "int8_t",
    "int32_t",
    "int64_t",
    "uint32_t",
    "uint64_t",
    "ostream",
    "istream",
    "optional",
];
static CPP: LanguageSpec = LanguageSpec {
    name: "C++",
    emoji: "➕",
    keywords: CPP_KEYWORDS,
    types: CPP_TYPES,
    line_comment: "//",
    block_comment: Some(("/*", "*/")),
    single_quote: SingleQuote::Char,
    backtick_string: false,
    lifetimes: false,
    macros: false,
    rust_attributes: false,
    preprocessor: true,
    decorators: false,
    indent_spaces: 4,
    samples: samples::cpp::SAMPLES,
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_languages_have_data() {
        assert_eq!(ALL.len(), 10);
        for &lang in ALL {
            let spec = lang.spec();
            assert!(!spec.name.is_empty());
            assert!(!spec.keywords.is_empty(), "{} has no keywords", spec.name);
            assert!(!spec.samples.is_empty(), "{} has no samples", spec.name);
        }
    }

    #[test]
    fn names_match() {
        assert_eq!(Language::Rust.name(), "Rust");
        assert_eq!(Language::Cpp.name(), "C++");
        assert_eq!(Language::JavaScript.name(), "JavaScript");
    }
}
